name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: eine/setup-msys2@v1
      with:
        msystem: MINGW32
        release: false
        update: false
        cache: false
        install: 'mingw-w64-i686-gcc mingw-w64-i686-wxWidgets make'
    - name: Create build files
      shell: cmd
      run: create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl
    - name: Build
      shell: msys2 {0}
      run: ./.github/workflows/msys2.sh
    - name: Create source package
      shell: cmd
      run: |
        cd install/windows
        create_source_package.bat
    - name: Create installer
      shell: cmd
      run: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" install/windows/wxFormBuilder.iss'
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Windows
        path: install\windows\wxFormBuilder_v3.9.0.exe
